services:
  wordpress:
    build: 
      context: ./services/wordpress
      args:
        MYSQL_DATABASE: wp
        MYSQL_USER: wp
        MYSQL_PASSWORD: wp
        MYSQL_HOST: db
        # GitHub Codespaces で利用する:
        # WP_CONFIG_EXTRA: "wp-config-extra-github-codespaces.txt"
        # 指定しなかったときのデフォルト値は "php.ini-developent":
        # PHP_INI_FILE: "php.ini-production"
        PHP_INI_EXTRA: |
          post_max_size = 20M
          upload_max_filesize = 20M
        # バージョンを指定する（デフォルト: `latest` ）:
        # - RC 版: `6.5-RC1` など
        # - 開発版: `nightly`
        WORDPRESS_VERSION: "latest"
        # LOCALE を指定する（デフォルト: `en_JS` ）:
        # - 開発版などでは `ja` が使えないことがあります
        WORDPRESS_LOCALE: "ja"
    ports:
      - "80:80"
    volumes:
      - wordpress_uploads:/var/www/html/wp-content/uploads
  db:
    build: ./services/db
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_DATABASE: wp
      MYSQL_USER: wp
      MYSQL_PASSWORD: wp
    volumes:
      - db_data:/var/lib/mysql

volumes:
  wordpress_uploads:
  db_data:
