services:
  wordpress:
    build: 
      context: ./services/wordpress
      args:
        MYSQL_DATABASE: wp
        MYSQL_USER: wp
        MYSQL_PASSWORD: wp
        MYSQL_HOST: db
    ports:
      - "80:80"
  db:
    build: ./services/db
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: 1
      MARIADB_DATABASE: wp
      MARIADB_USER: wp
      MARIADB_PASSWORD: wp
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
